DATA_LOOKBACK_DAYS = 30
DEFAULT_DATASOURCE = "F28_PROD_XEUS"
DEFAULT_OUTPUT = "final_with_row_20_200.csv"
PRIOR_MEAN_WINDOW = "7d"
SHORT_ROLLING_WINDOW = 20
LONG_ROLLING_WINDOW = 200
DELTA_THRESHOLD = 0.004
PERSISTENT_FLAG_MIN_POINTS = 10
RECENT_FLAG_HOURS = 12

DELTA_FLAG_COLUMN = f"delta_gt_{str(DELTA_THRESHOLD).replace('.', '_')}"
PERSISTENT_FLAG_COLUMN = f"persistent_delta_{PERSISTENT_FLAG_MIN_POINTS}"